using UnityEngine;

namespace Drone.Runtime.FlightModes
{
    /// <summary>
    /// Motor mixing strategy prioritization policy when motor saturation occurs.
    /// </summary>
    public enum MixingStrategy
    {
        PrioritizeThrottle,
        PrioritizeAttitude
    }

    /// <summary>
    /// Snapshot of drone physical state passed to flight controllers each physics update.
    /// </summary>
    [System.Serializable]
    public struct DroneState
    {
        public Vector3 Rotation;
        public Vector3 AngularVelocity;
        public Vector3 Velocity;
        public float VerticalVelocity;
        public float UpDot;
    }

    /// <summary>
    /// Output commands generated by a flight mode (3-axis angular rates and normalized throttle).
    /// </summary>
    [System.Serializable]
    public struct FlightControlOutput
    {
        public Vector3 TargetRate;
        public float Throttle;
        public Vector2 TargetAngles;
    }

    /// <summary>
    /// Common interface for modular drone flight modes (Acro, Angle, Velocity, Waypoint).
    /// </summary>
    public interface IFlightMode
    {
        /// <summary>
        /// Evaluates current stick inputs and kinematics state to compute attitude rate demands and throttle.
        /// </summary>
        /// <param name="inputs">Current normalized control stick inputs.</param>
        /// <param name="state">Current physical drone kinematics state.</param>
        /// <param name="dt">Physics timestep in seconds.</param>
        /// <returns>FlightControlOutput containing demanded rates and collective throttle.</returns>
        FlightControlOutput Calculate(DroneInputs inputs, DroneState state, float dt);

        /// <summary>
        /// Resets internal controller integrators and filter memory.
        /// </summary>
        void Reset();

        string ModeName { get; }
        MixingStrategy Mixing { get; }
    }
}
