using UnityEngine;

/// <summary>
/// Manages drone physical properties (mass, damping) and applies motor thrust/torque to the Rigidbody.
/// </summary>
[RequireComponent(typeof(Rigidbody))]
public class DroneHardware : MonoBehaviour
{
    [Header("Drone Physics")]
    [Tooltip("Total mass of the drone in kilograms.")]
    public float mass = 1f;

    [Tooltip("Reaction torque multiplier generated by propeller differential drag.")]
    public float torqueFactor = 0.02f;

    [Range(0f, 1f)]
    [Tooltip("Linear damping applied to the Rigidbody to resist drift.")]
    public float linearDamping = 0.2f;

    [Range(0f, 5f)]
    [Tooltip("Angular damping applied to the Rigidbody to stabilize attitude oscillations.")]
    public float angularDamping = 1.0f;

    [Header("Motor References")]
    [Tooltip("Front-Left motor Transform. Auto-detected by name if unassigned.")]
    public Transform frontLeft;

    [Tooltip("Front-Right motor Transform. Auto-detected by name if unassigned.")]
    public Transform frontRight;

    [Tooltip("Back-Left motor Transform. Auto-detected by name if unassigned.")]
    public Transform backLeft;

    [Tooltip("Back-Right motor Transform. Auto-detected by name if unassigned.")]
    public Transform backRight;

    [Header("Runtime Motor Forces (Read Only)")]
    public float FLForce;
    public float FRForce;
    public float BLForce;
    public float BRForce;

    private Rigidbody rb;

    /// <summary>
    /// Configures Rigidbody mass, damping, center of mass, and automatically resolves motor transforms.
    /// </summary>
    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
        if (rb != null)
        {
            rb.isKinematic = false;
            rb.useGravity = true;
            rb.mass = mass;
            rb.linearDamping = linearDamping;
            rb.angularDamping = angularDamping;
            // Offset center of mass slightly below thrust plane for physical pendulum self-righting stability
            rb.centerOfMass = new Vector3(0f, -0.05f, 0f);
        }

        AutoDetectMotorTransforms();
    }

    /// <summary>
    /// Applies physical mass and damping configuration centrally from DroneDirector.
    /// </summary>
    public void ApplyHardwareSettings(float mass, float linearDamping, float angularDamping)
    {
        this.mass = mass;
        this.linearDamping = linearDamping;
        this.angularDamping = angularDamping;

        if (rb == null)
            rb = GetComponent<Rigidbody>();

        if (rb != null)
        {
            rb.mass = mass;
            rb.linearDamping = linearDamping;
            rb.angularDamping = angularDamping;
            rb.centerOfMass = new Vector3(0f, -0.05f, 0f);
        }
    }

    /// <summary>
    /// Scans child transforms to locate and assign motor references if left unassigned in the Inspector.
    /// Matches FLPropeller, FRPropeller, BlPropeller, BRPropeller, or standard abbreviations.
    /// </summary>
    private void AutoDetectMotorTransforms()
    {
        Transform[] children = GetComponentsInChildren<Transform>(true);
        foreach (Transform child in children)
        {
            if (child == transform) continue;
            string name = child.name.Trim().ToLowerInvariant();

            if (frontLeft == null && (name == "fl" || name.StartsWith("fl") || name.Contains("frontleft") || name.Contains("front_left")))
                frontLeft = child;
            else if (frontRight == null && (name == "fr" || name.StartsWith("fr") || name.Contains("frontright") || name.Contains("front_right")))
                frontRight = child;
            else if (backLeft == null && (name == "bl" || name.StartsWith("bl") || name.Contains("backleft") || name.Contains("back_left") || name.Contains("rearleft")))
                backLeft = child;
            else if (backRight == null && (name == "br" || name.StartsWith("br") || name.Contains("backright") || name.Contains("back_right") || name.Contains("rearright")))
                backRight = child;
        }
    }

    /// <summary>
    /// Applies individual motor thrust forces at propeller positions (or geometric fallback corners) and relative yaw torque to the Rigidbody.
    /// </summary>
    /// <param name="fl">Front-Left motor thrust force in Newtons.</param>
    /// <param name="fr">Front-Right motor thrust force in Newtons.</param>
    /// <param name="bl">Back-Left motor thrust force in Newtons.</param>
    /// <param name="br">Back-Right motor thrust force in Newtons.</param>
    public void ApplyMotorForces(float fl, float fr, float bl, float br)
    {
        FLForce = fl;
        FRForce = fr;
        BLForce = bl;
        BRForce = br;

        if (rb == null)
        {
            return;
        }

        Vector3 forceDirection = transform.up;

        // Use resolved propeller transforms or calculate geometric quadcopter corner offsets
        Vector3 flPos = frontLeft != null ? frontLeft.position : transform.TransformPoint(new Vector3(-0.35f, 0.05f, 0.35f));
        Vector3 frPos = frontRight != null ? frontRight.position : transform.TransformPoint(new Vector3(0.35f, 0.05f, 0.35f));
        Vector3 blPos = backLeft != null ? backLeft.position : transform.TransformPoint(new Vector3(-0.35f, 0.05f, -0.35f));
        Vector3 brPos = backRight != null ? backRight.position : transform.TransformPoint(new Vector3(0.35f, 0.05f, -0.35f));

        rb.AddForceAtPosition(forceDirection * FLForce, flPos, ForceMode.Force);
        rb.AddForceAtPosition(forceDirection * FRForce, frPos, ForceMode.Force);
        rb.AddForceAtPosition(forceDirection * BLForce, blPos, ForceMode.Force);
        rb.AddForceAtPosition(forceDirection * BRForce, brPos, ForceMode.Force);

        float yawTorque = (-FLForce * torqueFactor)
            + (FRForce * torqueFactor)
            + (BLForce * torqueFactor)
            - (BRForce * torqueFactor);

        rb.AddRelativeTorque(Vector3.up * yawTorque, ForceMode.Force);
    }
}
