using UnityEngine;

/// <summary>
/// Manages drone physical properties (mass, damping) and applies motor thrust/torque to the Rigidbody.
/// </summary>
[RequireComponent(typeof(Rigidbody))]
public class DroneHardware : MonoBehaviour
{
    [Header("Drone Physics")]
    [Tooltip("Total mass of the drone in kilograms.")]
    public float mass = 1f;

    [Tooltip("Reaction torque multiplier generated by propeller differential drag.")]
    public float torqueFactor = 0.02f;

    [Range(0f, 1f)]
    [Tooltip("Linear damping applied to the Rigidbody to resist drift.")]
    public float linearDamping = 0.2f;

    [Header("Motor References")]
    [Tooltip("Front-Left motor Transform. Auto-detected by name if unassigned.")]
    public Transform frontLeft;

    [Tooltip("Front-Right motor Transform. Auto-detected by name if unassigned.")]
    public Transform frontRight;

    [Tooltip("Back-Left motor Transform. Auto-detected by name if unassigned.")]
    public Transform backLeft;

    [Tooltip("Back-Right motor Transform. Auto-detected by name if unassigned.")]
    public Transform backRight;

    [Header("Runtime Motor Forces (Read Only)")]
    public float FLForce;
    public float FRForce;
    public float BLForce;
    public float BRForce;

    private Rigidbody rb;

    /// <summary>
    /// Configures Rigidbody mass, damping, and automatically resolves unassigned motor transforms.
    /// </summary>
    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
        if (rb != null)
        {
            rb.mass = mass;
            rb.linearDamping = linearDamping;
        }

        AutoDetectMotorTransforms();
    }

    /// <summary>
    /// Scans child transforms to locate and assign motor references if left unassigned in the Inspector.
    /// </summary>
    private void AutoDetectMotorTransforms()
    {
        Transform[] children = GetComponentsInChildren<Transform>(true);
        foreach (Transform child in children)
        {
            if (child == transform) continue;
            string name = child.name.Trim().ToLowerInvariant();

            if (frontLeft == null && (name == "fl" || name.Contains("frontleft") || name.Contains("front_left")))
                frontLeft = child;
            else if (frontRight == null && (name == "fr" || name.Contains("frontright") || name.Contains("front_right")))
                frontRight = child;
            else if (backLeft == null && (name == "bl" || name.Contains("backleft") || name.Contains("back_left") || name.Contains("rearleft")))
                backLeft = child;
            else if (backRight == null && (name == "br" || name.Contains("backright") || name.Contains("back_right") || name.Contains("rearright")))
                backRight = child;
        }

        if (frontLeft == null || frontRight == null || backLeft == null || backRight == null)
        {
            Debug.LogWarning($"[DroneHardware] One or more motor transforms could not be resolved on {name}. Motor forces may not apply correctly.", this);
        }
    }

    /// <summary>
    /// Applies individual motor thrust forces at propeller positions and relative yaw torque to the Rigidbody.
    /// </summary>
    /// <param name="fl">Front-Left motor thrust force in Newtons.</param>
    /// <param name="fr">Front-Right motor thrust force in Newtons.</param>
    /// <param name="bl">Back-Left motor thrust force in Newtons.</param>
    /// <param name="br">Back-Right motor thrust force in Newtons.</param>
    public void ApplyMotorForces(float fl, float fr, float bl, float br)
    {
        FLForce = fl;
        FRForce = fr;
        BLForce = bl;
        BRForce = br;

        if (rb == null || frontLeft == null || frontRight == null || backLeft == null || backRight == null)
        {
            return;
        }

        Vector3 forceDirection = transform.up;

        rb.AddForceAtPosition(forceDirection * FLForce, frontLeft.position, ForceMode.Force);
        rb.AddForceAtPosition(forceDirection * FRForce, frontRight.position, ForceMode.Force);
        rb.AddForceAtPosition(forceDirection * BLForce, backLeft.position, ForceMode.Force);
        rb.AddForceAtPosition(forceDirection * BRForce, backRight.position, ForceMode.Force);

        float yawTorque = (-FLForce * torqueFactor)
            + (FRForce * torqueFactor)
            + (BLForce * torqueFactor)
            - (BRForce * torqueFactor);

        rb.AddRelativeTorque(Vector3.up * yawTorque, ForceMode.Force);
    }
}
